package org.eclipse.osgi.technology.opentelemetry.weaver.scr;

import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.commons.AdviceAdapter;

/**
 * ASM {@link AdviceAdapter} that wraps a DS lifecycle method with OpenTelemetry
 * instrumentation by delegating to {@link ScrInstrumentationHelper}.
 * <p>
 * The lifecycle action (activate, deactivate, modified, constructor) is
 * determined by {@link ScrClassVisitor} from the DS XML descriptor and
 * passed directly to this visitor — no annotation scanning is needed.
 * <p>
 * The generated bytecode is equivalent to:
 * <pre>
 * Object[] ctx = ScrInstrumentationHelper.onLifecycleEnter(
 *     componentName, className, methodName, action);
 * try {
 *     // original method body
 * } catch (Throwable t) {
 *     ScrInstrumentationHelper.onLifecycleError(ctx, t);
 *     throw t;
 * } finally {
 *     ScrInstrumentationHelper.onLifecycleExit(ctx);
 * }
 * </pre>
 */
class ScrMethodVisitor extends AdviceAdapter {

    private static final String HELPER =
            "org/eclipse/osgi/technology/opentelemetry/weaver/scr/ScrInstrumentationHelper";

    private final String className;
    private final String methodName;
    private final String componentName;
    private final String action;
    private int contextLocal;

    ScrMethodVisitor(MethodVisitor mv, int access, String name,
            String descriptor, String className, String componentName,
            String action) {
        super(Opcodes.ASM9, mv, access, name, descriptor);
        this.className = className;
        this.methodName = name;
        this.componentName = componentName;
        this.action = action;
    }

    @Override
    protected void onMethodEnter() {
        contextLocal = newLocal(Type.getType("[Ljava/lang/Object;"));

        visitLdcInsn(componentName);
        visitLdcInsn(className.replace('/', '.'));
        visitLdcInsn("<init>".equals(methodName) ? "<init>" : methodName);
        visitLdcInsn(action);
        visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onLifecycleEnter",
                "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Object;",
                false);
        storeLocal(contextLocal);
    }

    @Override
    protected void onMethodExit(int opcode) {
        if (opcode == ATHROW) {
            dup();
            int exLocal = newLocal(Type.getType("Ljava/lang/Throwable;"));
            storeLocal(exLocal);
            loadLocal(contextLocal);
            loadLocal(exLocal);
            visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onLifecycleError",
                    "([Ljava/lang/Object;Ljava/lang/Throwable;)V", false);
        }
        loadLocal(contextLocal);
        visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onLifecycleExit",
                "([Ljava/lang/Object;)V", false);
    }
}
