package org.eclipse.osgi.technology.opentelemetry.weaver.jdbc;

import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.commons.AdviceAdapter;

/**
 * ASM {@link AdviceAdapter} that wraps JDBC execute methods with
 * OpenTelemetry instrumentation by delegating to {@link JdbcInstrumentationHelper}.
 * The generated bytecode is equivalent to:
 * <pre>
 * Object[] ctx = JdbcInstrumentationHelper.onExecuteEnter(sql, "executeQuery", "com.example.MyStatement");
 * try {
 *     // original method body
 * } catch (Throwable t) {
 *     JdbcInstrumentationHelper.onExecuteError(ctx, t);
 *     throw t;
 * } finally {
 *     JdbcInstrumentationHelper.onExecuteExit(ctx);
 * }
 * </pre>
 */
class JdbcMethodVisitor extends AdviceAdapter {

    private static final String HELPER =
            "org/eclipse/osgi/technology/opentelemetry/weaver/jdbc/JdbcInstrumentationHelper";

    private final String className;
    private final String methodName;
    private final boolean hasSqlParam;
    private int contextLocal;

    JdbcMethodVisitor(MethodVisitor mv, int access, String name,
            String descriptor, String className, boolean hasSqlParam) {
        super(Opcodes.ASM9, mv, access, name, descriptor);
        this.className = className;
        this.methodName = name;
        this.hasSqlParam = hasSqlParam;
    }

    @Override
    protected void onMethodEnter() {
        contextLocal = newLocal(Type.getType("[Ljava/lang/Object;"));

        if (hasSqlParam) {
            loadArg(0);
        } else {
            visitInsn(ACONST_NULL);
        }
        visitLdcInsn(methodName);
        visitLdcInsn(className.replace('/', '.'));
        visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onExecuteEnter",
                "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Object;",
                false);
        storeLocal(contextLocal);
    }

    @Override
    protected void onMethodExit(int opcode) {
        if (opcode == ATHROW) {
            dup();
            int exLocal = newLocal(Type.getType("Ljava/lang/Throwable;"));
            storeLocal(exLocal);
            loadLocal(contextLocal);
            loadLocal(exLocal);
            visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onExecuteError",
                    "([Ljava/lang/Object;Ljava/lang/Throwable;)V", false);
        }
        loadLocal(contextLocal);
        visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onExecuteExit",
                "([Ljava/lang/Object;)V", false);
    }
}
