package org.eclipse.osgi.technology.opentelemetry.weaving.jakarta.servlet;

import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.commons.AdviceAdapter;

/**
 * ASM {@link AdviceAdapter} that wraps {@code HttpServlet} handler methods with
 * OpenTelemetry instrumentation by delegating to {@link ServletInstrumentationHelper}.
 * <p>
 * The generated bytecode is equivalent to:
 * <pre>
 * Object[] spanAndScope = ServletInstrumentationHelper.onServiceEnter(req, this.getClass().getName());
 * try {
 *     // original method body
 * } catch (Throwable t) {
 *     ServletInstrumentationHelper.onServiceError(spanAndScope, t);
 *     throw t;
 * } finally {
 *     ServletInstrumentationHelper.onServiceExit(spanAndScope, resp);
 * }
 * </pre>
 */
class ServletServiceMethodVisitor extends AdviceAdapter {

    private static final String HELPER = "org/eclipse/osgi/technology/opentelemetry/weaving/jakarta/servlet/ServletInstrumentationHelper";

    private final String className;
    private int spanAndScopeLocal;

    ServletServiceMethodVisitor(MethodVisitor mv, int access, String name,
            String descriptor, String className) {
        super(Opcodes.ASM9, mv, access, name, descriptor);
        this.className = className;
    }

    @Override
    protected void onMethodEnter() {
        // Object[] spanAndScope = ServletInstrumentationHelper.onServiceEnter(req, className)
        spanAndScopeLocal = newLocal(org.objectweb.asm.Type.getType("[Ljava/lang/Object;"));

        loadArg(0); // req (first arg)
        visitLdcInsn(className.replace('/', '.'));
        visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onServiceEnter",
                "(Ljakarta/servlet/http/HttpServletRequest;Ljava/lang/String;)[Ljava/lang/Object;",
                false);
        storeLocal(spanAndScopeLocal);
    }

    @Override
    protected void onMethodExit(int opcode) {
        if (opcode == ATHROW) {
            // Exception on stack: dup, record error, then call exit
            dup();
            int exLocal = newLocal(org.objectweb.asm.Type.getType("Ljava/lang/Throwable;"));
            storeLocal(exLocal);
            loadLocal(spanAndScopeLocal);
            loadLocal(exLocal);
            visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onServiceError",
                    "([Ljava/lang/Object;Ljava/lang/Throwable;)V", false);
        }
        // Always call onServiceExit
        loadLocal(spanAndScopeLocal);
        loadArg(1); // resp
        visitMethodInsn(Opcodes.INVOKESTATIC, HELPER, "onServiceExit",
                "([Ljava/lang/Object;Ljakarta/servlet/http/HttpServletResponse;)V", false);
    }
}
